/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ReplaceInCodeBlockPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  placeholderPrefix: "<"
};
var pairedSuffix = {
  "<": ">",
  "{": "}",
  "[": "]",
  "(": ")",
  "{{": "}}",
  "[[": "]]",
  "((": "))"
};
var ReplaceInCodeBlockPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    const pending = await this.app.loadLocalStorage("replace-pencil-reset-pending");
    if (pending === "true") {
      new import_obsidian.Notice("Done reset!");
      this.app.saveLocalStorage("replace-pencil-reset-pending", null);
    }
    this.addRibbonIcon("eraser", "Reset all replace-pencil block", async () => {
      this.app.saveLocalStorage("replace-pencil-reset-pending", "true");
      location.reload();
    });
    this.addSettingTab(new ReplaceSettingTab(this.app, this));
    this.addCommand({
      id: "replace-pencil-reset",
      name: "reset replace-pencil blocks",
      callback: async () => {
        this.app.saveLocalStorage("replace-pencil-reset-pending", "true");
        location.reload();
      }
    });
    this.registerMarkdownPostProcessor((el, ctx) => {
      const preBlocks = el.querySelectorAll("pre");
      preBlocks.forEach((preEl) => {
        const codeEl = preEl.querySelector("code");
        if (!codeEl)
          return;
        const prefix = this.settings.placeholderPrefix || "<";
        const suffix = pairedSuffix[prefix];
        if (!suffix) {
          new import_obsidian.Notice(`Unsupported placeholder prefix: ${prefix}`);
          return;
        }
        const escapedPrefix = prefix.replace(/[-\/\\^$*+?.()|[\]{}]/g, "\\$&");
        const escapedSuffix = suffix.replace(/[-\/\\^$*+?.()|[\]{}]/g, "\\$&");
        const pattern = new RegExp(`${escapedPrefix}([\\w\\-]+)${escapedSuffix}`, "g");
        const originalText = codeEl.textContent || "";
        const varMatches = Array.from(new Set(originalText.match(pattern) || []));
        if (!varMatches.length)
          return;
        preEl.classList.add("replace-pencil-pre");
        const vars = {};
        const container = createDiv({ cls: "replace-pencil-container" });
        preEl.insertAdjacentElement("beforebegin", container);
        varMatches.forEach((match) => {
          const key = match.slice(prefix.length, match.length - suffix.length);
          vars[key] = "";
          const inputWrapper = createDiv({ cls: "replace-pencil-input-wrapper" });
          const input = createEl("input", {
            type: "text",
            cls: "replace-pencil-input",
            attr: { placeholder: key }
          });
          this.registerDomEvent(input, "input", () => {
            vars[key] = input.value;
            renderCode();
          });
          const clearButton = createEl("button", {
            text: "Clear",
            cls: "replace-pencil-clear-button"
          });
          this.registerDomEvent(clearButton, "click", () => {
            input.value = "";
            vars[key] = "";
            renderCode();
          });
          inputWrapper.appendChild(input);
          inputWrapper.appendChild(clearButton);
          container.appendChild(inputWrapper);
        });
        const copyButton = createEl("button", {
          cls: "replace-pencil-copy-button",
          text: "Copy"
        });
        preEl.appendChild(copyButton);
        this.registerDomEvent(copyButton, "click", async () => {
          try {
            const text = generatePureText();
            await navigator.clipboard.writeText(text);
            copyButton.textContent = "Copied!";
            window.setTimeout(() => {
              copyButton.textContent = "Copy";
            }, 1500);
          } catch (e) {
            new import_obsidian.Notice("Failed to copy :(");
            console.error(e);
          }
        });
        const renderCode = () => {
          while (codeEl.firstChild)
            codeEl.removeChild(codeEl.firstChild);
          const fragments = originalText.split(
            new RegExp(`(${escapedPrefix}[\\w\\-]+${escapedSuffix})`, "g")
          );
          for (const frag of fragments) {
            const match = frag.match(
              new RegExp(`^${escapedPrefix}([\\w\\-]+)${escapedSuffix}$`)
            );
            if (match) {
              const key = match[1];
              const span = createSpan();
              if (vars[key]) {
                span.textContent = vars[key];
                span.className = "replace-pencil-replaced";
              } else {
                span.textContent = frag;
              }
              codeEl.appendChild(span);
            } else {
              codeEl.appendText(frag);
            }
          }
        };
        const generatePureText = () => {
          let result = originalText;
          Object.keys(vars).forEach((key) => {
            const regex = new RegExp(
              `${escapedPrefix}${key}${escapedSuffix}`,
              "g"
            );
            result = result.replace(regex, vars[key] || `${prefix}${key}${suffix}`);
          });
          return result;
        };
        renderCode();
      });
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ReplaceSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Placeholder prefix").addText(
      (text) => text.setPlaceholder("<").setValue(this.plugin.settings.placeholderPrefix).onChange(async (value) => {
        const trimmed = value.trim();
        this.plugin.settings.placeholderPrefix = trimmed || "<";
        await this.plugin.saveSettings();
      })
    ).descEl.appendChild(createFragment((frag) => {
      frag.appendText("Prefix used for variable placeholders. Only use one of: <, {, [, ( or their doubled versions like {{.");
      frag.appendChild(createEl("br"));
      frag.appendText("Use the 'eraser' button or command palette to reload and apply.");
    }));
  }
};


/* nosourcemap */